version: '3'

services:

    redis:
        restart: always
        hostname: redis
        image: redis:rc-alpine3.11

    api:
        build: api
        volumes:
            - ./:/app
        command: python3 -m api.greetings
        ports:
            - "8080:8080"
        depends_on:
            -  redis
        restart: on-failure

    front:
        build:
            context: front
            dockerfile: Dockerfile
        stdin_open: true
        volumes:
            - ./front:/front
            - ./front/node_modules:/front/node_modules
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
